const output=document.querySelector("#result");document.querySelector("#check").onclick=()=>{output.textContent=JSON.stringify({secure:isSecureContext,serviceWorker:"serviceWorker"in navigator,notification:"Notification"in window,pushManager:"PushManager"in window,standalone:matchMedia("(display-mode: standalone)").matches,permission:"Notification"in window?Notification.permission:"indisponível"},null,2)};document.querySelector("#notify").onclick=async()=>{try{if(!("Notification"in window))throw Error("Abre esta aplicação pelo ícone do ecrã principal.");const reg=await navigator.serviceWorker.register("./sw.js",{scope:"./"});let permission=Notification.permission;if(permission==="default")permission=await Notification.requestPermission();if(permission!=="granted")throw Error("Permissão não concedida: "+permission);await reg.showNotification("🐾 Teste Push",{body:"Notificação de teste no iPhone!",tag:"push-lab-test"});output.textContent="Notificação enviada ao sistema. Verifica o Centro de Notificações."}catch(e){output.textContent="Erro: "+e.message}};

const client=window.supabase.createClient("https://uoafurfydkhcycwobeil.supabase.co","sb_publishable_YtaQWacLc1MVuYCGmK341Q_M2Gomkqg",{auth:{storageKey:"push-lab-auth-v1"}});
const vapid="BDd2LQbHeHnGNhZFgBVZM_FueyjSgcRw5txOxobsKq-v8JlUPUuS54OKsixu0gID7qmknqpzQg8X9L4QCwnmog8";
const bytes=s=>Uint8Array.from(atob(s.replace(/-/g,"+").replace(/_/g,"/")),c=>c.charCodeAt(0));
const subscribeButton=document.querySelector("#subscribe");
client.auth.getSession().then(({data})=>{subscribeButton.disabled=!data.session});
document.querySelector("#login").onclick=async()=>{const {error}=await client.auth.signInWithPassword({email:document.querySelector("#email").value.trim(),password:document.querySelector("#password").value});document.querySelector("#password").value="";subscribeButton.disabled=!!error;output.textContent=error?"Erro ao iniciar sessão: "+error.message:"Sessão iniciada. Podes registar este iPhone."};
subscribeButton.onclick=async()=>{try{const {data:{session}}=await client.auth.getSession();if(!session)throw Error("Inicia sessão primeiro.");if(!("PushManager"in window))throw Error("Abre pelo ícone do ecrã principal no iPhone.");const reg=await navigator.serviceWorker.register("./sw.js",{scope:"./"});const permission=await Notification.requestPermission();if(permission!=="granted")throw Error("Notificações não autorizadas.");let sub=await reg.pushManager.getSubscription();if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:bytes(vapid)});const response=await fetch("https://uoafurfydkhcycwobeil.supabase.co/functions/v1/push-register",{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+session.access_token,"apikey":"sb_publishable_YtaQWacLc1MVuYCGmK341Q_M2Gomkqg"},body:JSON.stringify(sub.toJSON())});const result=await response.json();if(!response.ok)throw Error(result.error||"Erro HTTP "+response.status);output.textContent="Subscrição registada com sucesso no Supabase!";}catch(e){output.textContent="Erro: "+e.message}};

const sendButton=document.querySelector("#send");
client.auth.getSession().then(({data})=>{sendButton.disabled=!data.session});
client.auth.onAuthStateChange((_event,session)=>{sendButton.disabled=!session});
sendButton.onclick=async()=>{try{sendButton.disabled=true;output.textContent="A enviar Push remoto...";const {data:{session}}=await client.auth.getSession();if(!session)throw Error("Inicia sessão primeiro.");const response=await fetch("https://uoafurfydkhcycwobeil.supabase.co/functions/v1/push-send-test",{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+session.access_token,"apikey":"sb_publishable_YtaQWacLc1MVuYCGmK341Q_M2Gomkqg"},body:"{}"});const result=await response.json();output.textContent=JSON.stringify(result,null,2);if(!response.ok)output.textContent="Erro HTTP "+response.status+": "+output.textContent;}catch(e){output.textContent="Erro: "+e.message}finally{sendButton.disabled=false}};

document.querySelector("#refresh-sw").onclick=async()=>{try{output.textContent="A verificar atualização das notificações...";const reg=await navigator.serviceWorker.register("./sw.js",{scope:"./",updateViaCache:"none"});await reg.update();if(reg.waiting){reg.waiting.postMessage({type:"SKIP_WAITING"})}output.textContent="Atualização solicitada. Fecha e volta a abrir o Teste Push; depois envia uma nova notificação e toca nela."}catch(e){output.textContent="Erro ao atualizar: "+e.message}};

navigator.serviceWorker?.addEventListener("message",event=>{if(event.data?.type==="SW_VERSION")output.textContent="Versão ativa: "+event.data.version;if(event.data?.type==="PUSH_CLICK")output.textContent="Toque detetado pela versão "+event.data.version+". Destino: "+event.data.target});
document.querySelector("#diagnose-sw").onclick=async()=>{try{const reg=await navigator.serviceWorker.getRegistration("./");if(!reg?.active)throw Error("Ainda não há Service Worker ativo. Carrega em Atualizar notificações.");output.textContent="A consultar versão ativa...";reg.active.postMessage({type:"GET_VERSION"});setTimeout(()=>{if(output.textContent==="A consultar versão ativa...")output.textContent="A versão ativa não respondeu. Carrega em Atualizar notificações e volta a abrir a aplicação."},1800)}catch(e){output.textContent="Erro: "+e.message}};


async function simulateShift(date){try{output.textContent="A consultar o turno no Supabase...";const {data:{session}}=await client.auth.getSession();if(!session)throw Error("Faz login primeiro.");const response=await fetch("https://uoafurfydkhcycwobeil.supabase.co/functions/v1/push-shift-preview",{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+session.access_token,"apikey":"sb_publishable_YtaQWacLc1MVuYCGmK341Q_M2Gomkqg"},body:JSON.stringify({simulatedDate:date})});const result=await response.json();output.textContent=(response.ok?"SIMULAÇÃO — ":"ERRO HTTP "+response.status+" — ")+JSON.stringify(result,null,2)}catch(e){output.textContent="Erro na simulação: "+e.message}}
document.querySelector("#simulate-shift").onclick=()=>simulateShift("2026-10-11");
document.querySelector("#simulate-off").onclick=()=>simulateShift("2026-10-10");
